### ISSUE TITLE
problem with getDownloadUrl

### ISSUE THREAD

**Issue by coder63480** [firebase/codelab-friendlychat-android#107]
Hello I have a problem with getDownloadUrl. Can you help me? I work 2 days to fix it but it dosen´t work.

        private void saveToStories() { final DatabaseReference userStoryDb = FirebaseDatabase.getInstance().getReference().child("users").child(Uid).child("story");
        final String key = userStoryDb.push().getKey();

        StorageReference filePath = FirebaseStorage.getInstance().getReference().child("captures").child(key);

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        rotateBitmap.compress(Bitmap.CompressFormat.JPEG, 20, baos);
        byte[] dataToUpload = baos.toByteArray();
        UploadTask uploadTask = filePath.putBytes(dataToUpload);

        uploadTask.addOnSuccessListener(new OnSuccessListener<UploadTask.TaskSnapshot>() {
            @Override
            public void onSuccess(UploadTask.TaskSnapshot taskSnapshot) {
                Uri imageUrl = taskSnapshot.getDownloadUrl();
                                //here is the problem with getDownloadUrl()

                Long currentTimestamp = System.currentTimeMillis();
                Long endTimestamp = currentTimestamp + (24*60*60*1000);

                Map<String, Object> mapToUpload = new HashMap<>();
                mapToUpload.put("imageUrl", imageUrl.toString());
                mapToUpload.put("timestampBeg", currentTimestamp);
                mapToUpload.put("timestampEnd", endTimestamp);

                userStoryDb.child(key).setValue(mapToUpload);

                finish();
                return;
            }
        });

        uploadTask.addOnFailureListener(new OnFailureListener() {
            @Override
            public void onFailure(@NonNull Exception e) {
                finish();
                return;
            }
        });
    }

**Comment by samtstern** [comment]
@coder63480 sorry for the slow response here.  Are you still having this issue?  If so what's the problem you've having with `getDownlaodUrl`?  It's not very clear from this post.

**Comment by coder63480** [comment]
I can‘t save a picture in the Firebase. I write under the problem „Herr is the Problem with getDownloadUrl()“ I hope you can help me

**Comment by samtstern** [comment]
@coder63480 I'm sorry this still doesn't say *what* the problem is or why you expected different behavior.  `getDownloadUrl()` is only used once in this codelab and as you can see it's an async action:
https://github.com/firebase/codelab-friendlychat-android/blob/5994062d2b6f455bf264bff12da20e7d6ad7ff9c/build-android/app/src/main/java/com/google/firebase/codelab/friendlychat/MainActivity.java#L185

You're trying to call `getDownloadUrl()` on `UploadTask.TaskSnapshot` where it is not available:
https://firebase.google.com/docs/reference/android/com/google/firebase/storage/UploadTask.TaskSnapshot
