### ISSUE TITLE
I have a problem. The app is sending messages to Firebase realtime database. I sent 3 messages and they showed up in the firebase console (database). But none of the messages shows in the app. The view is empty

### ISSUE THREAD

**Issue by giovanavg** [firebase/codelab-friendlychat-android#132]

**Comment by samtstern** [comment]
@giovanavg this is not enough information to help you!  Please fill out the issue body with some debugging information, we can't guess the problem from the title.

See this link for more instructions:
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by jackx99** [comment]
It will not show up because the listener is placed on `onResume`. It should be on `onStart`. move also the line in `onPause` to `onStop`.

**Comment by jackx99** [comment]
I put `adapter.startListening()` to onStart instead of onResume likewise; onPause to onStop.

**Comment by amaan118921** [comment]
Same issue with me.

- The code provided in the codelab to read data from firebase and to show up in the app doesn't work.
- When I insert the data manually in firebase, the app's screen remains blank, the data is not showing up.
- And also the method startActivityforResult used in google authentication is now deprecated and it's not updated in the codelab.
- Now instead of that method we have to use registerForActivityResult and a little more.

These are the problems that I have faced in the codelab till now.

**Comment by krishkeerthiz** [comment]
> 
> 
> Same issue with me.
> 
>     * The code provided in the codelab to read data from firebase and to show up in the app doesn't work.
> 
>     * When I insert the data manually in firebase, the app's screen remains blank, the data is not showing up.
> 
>     * And also the method startActivityforResult used in google authentication is now deprecated and it's not updated in the codelab.
> 
>     * Now instead of that method we have to use registerForActivityResult and a little more.
> 
> 
> These are the problems that I have faced in the codelab till now.

Same problem to me also

**Comment by samtstern** [comment]
This codelab was significantly rewritten about 4 days ago:
https://github.com/firebase/codelab-friendlychat-android/pull/173

You may want to try again, I think a lot of those issues will be resolved.
